"""
Training loop for the Neural ODE surrogate.

Trains on HDF5 data generated by generate_training_data.py.
Uses teacher-forcing on sub-windows of trajectories for stability.

Usage:
    python -m neural_surrogate.train [--data training_data.h5] [--epochs 200]
"""

import torch
import torch.nn as nn
import numpy as np
import h5py
import os
import sys
import time
import argparse
import json
from torch.utils.data import Dataset, DataLoader

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from neural_surrogate.model import (
    HallowSurrogate, CLINICAL_KEYS, CLINICAL_WEIGHTS,
    N_CLINICAL, N_CRITICAL, CRITICAL_STATE_INDICES,
    LATENT_DIM, N_STATE, N_KNOBS,
)


class HallowTrajectoryDataset(Dataset):
    """Loads trajectory windows from the HDF5 training data."""

    def __init__(self, h5_path, window_size=24, stride=6, split='train',
                 train_frac=0.85):
        self.h5_path = h5_path
        self.window_size = window_size

        with h5py.File(h5_path, 'r') as f:
            n_total = f['knobs'].shape[0]
            n_timepoints = f['times'].shape[1]
            self.dt_output = float(f.attrs.get('dt_output', 1.0))

        n_train = int(n_total * train_frac)
        if split == 'train':
            self.sample_range = (0, n_train)
        else:
            self.sample_range = (n_train, n_total)

        # Build index of (sample_idx, time_start) windows
        self.windows = []
        for s in range(self.sample_range[0], self.sample_range[1]):
            for t_start in range(0, n_timepoints - window_size, stride):
                self.windows.append((s, t_start))

        # Compute normalization stats from training data
        self._compute_stats(h5_path, n_train)

    def _compute_stats(self, h5_path, n_train):
        """Compute mean/std for normalization from training split."""
        stats_cache = h5_path.replace('.h5', '_stats.npz')
        if os.path.exists(stats_cache):
            data = np.load(stats_cache)
            self.clinical_mean = data['clinical_mean']
            self.clinical_std = data['clinical_std']
            self.state_mean = data['state_mean']
            self.state_std = data['state_std']
            self.knob_mean = data['knob_mean']
            self.knob_std = data['knob_std']
            return

        with h5py.File(h5_path, 'r') as f:
            # Sample up to 500 trajectories for stats
            n_stat = min(n_train, 500)
            clinical = f['clinical'][:n_stat]  # (N, T, C)
            states = f['initial_state'][:n_stat]  # (N, 70)
            knobs = f['knobs'][:n_stat]  # (N, 4)

        # Clinical: compute over all time steps
        c_flat = clinical.reshape(-1, N_CLINICAL)
        self.clinical_mean = np.nanmean(c_flat, axis=0).astype(np.float32)
        self.clinical_std = np.nanstd(c_flat, axis=0).astype(np.float32)
        self.clinical_std[self.clinical_std < 1e-8] = 1.0

        self.state_mean = np.mean(states, axis=0).astype(np.float32)
        self.state_std = np.std(states, axis=0).astype(np.float32)
        self.state_std[self.state_std < 1e-8] = 1.0

        self.knob_mean = np.mean(knobs, axis=0).astype(np.float32)
        self.knob_std = np.std(knobs, axis=0).astype(np.float32)
        self.knob_std[self.knob_std < 1e-8] = 1.0

        np.savez(stats_cache,
                 clinical_mean=self.clinical_mean, clinical_std=self.clinical_std,
                 state_mean=self.state_mean, state_std=self.state_std,
                 knob_mean=self.knob_mean, knob_std=self.knob_std)

    def __len__(self):
        return len(self.windows)

    def __getitem__(self, idx):
        s, t_start = self.windows[idx]
        t_end = t_start + self.window_size

        with h5py.File(self.h5_path, 'r') as f:
            knobs = f['knobs'][s].astype(np.float32)
            times = f['times'][s, t_start:t_end].astype(np.float32)
            clinical = f['clinical'][s, t_start:t_end].astype(np.float32)
            crit_state = f['critical_state'][s, t_start:t_end].astype(np.float32)

            # Get the full state at window start for encoder input
            if t_start == 0:
                init_state = f['initial_state'][s].astype(np.float32)
            else:
                # For mid-trajectory windows, reconstruct from the full state
                # stored at each time point. We store critical state only,
                # so use initial_state as base and overlay critical vars.
                init_state = f['initial_state'][s].astype(np.float32)
                # Override critical state indices with actual values at t_start
                init_state[CRITICAL_STATE_INDICES] = crit_state[0]

        # Normalize
        knobs_n = (knobs - self.knob_mean) / self.knob_std
        state_n = (init_state - self.state_mean) / self.state_std
        clinical_n = (clinical - self.clinical_mean) / self.clinical_std

        # Normalize critical state per-variable
        crit_mean = self.state_mean[CRITICAL_STATE_INDICES]
        crit_std = self.state_std[CRITICAL_STATE_INDICES]
        crit_state_n = (crit_state - crit_mean) / crit_std

        # Relative time within window (start at 0)
        times_rel = times - times[0]

        return {
            'state': torch.from_numpy(state_n),
            'knobs': torch.from_numpy(knobs_n),
            'times': torch.from_numpy(times_rel),
            'clinical': torch.from_numpy(clinical_n),
            'critical_state': torch.from_numpy(crit_state_n),
        }


def build_weight_tensor():
    """Build per-output weight tensor from CLINICAL_WEIGHTS."""
    w = torch.ones(N_CLINICAL)
    for i, key in enumerate(CLINICAL_KEYS):
        w[i] = CLINICAL_WEIGHTS.get(key, 1.0)
    return w / w.mean()


def train(data_path, epochs=200, batch_size=64, lr=1e-3, window_size=24,
          stride=6, latent_dim=LATENT_DIM, save_dir=None, device=None):
    if device is None:
        # torchdiffeq uses float64 internally which MPS doesn't support.
        # Use CPU — model is small (176K params) so CPU is fast enough.
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Device: {device}")

    if save_dir is None:
        save_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                'checkpoints')
    os.makedirs(save_dir, exist_ok=True)

    # Datasets
    train_ds = HallowTrajectoryDataset(data_path, window_size=window_size,
                                        stride=stride, split='train')
    val_ds = HallowTrajectoryDataset(data_path, window_size=window_size,
                                      stride=stride, split='val')
    # Copy normalization stats from train to val
    val_ds.clinical_mean = train_ds.clinical_mean
    val_ds.clinical_std = train_ds.clinical_std
    val_ds.state_mean = train_ds.state_mean
    val_ds.state_std = train_ds.state_std
    val_ds.knob_mean = train_ds.knob_mean
    val_ds.knob_std = train_ds.knob_std

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                               num_workers=0, drop_last=True)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False,
                             num_workers=0)

    print(f"Train windows: {len(train_ds)}, Val windows: {len(val_ds)}")

    # Model
    model = HallowSurrogate(latent_dim=latent_dim).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {n_params:,}")

    optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs,
                                                            eta_min=lr * 0.01)

    clinical_weights = build_weight_tensor().to(device)

    # Save normalization stats alongside model
    norm_stats = {
        'clinical_mean': train_ds.clinical_mean.tolist(),
        'clinical_std': train_ds.clinical_std.tolist(),
        'state_mean': train_ds.state_mean.tolist(),
        'state_std': train_ds.state_std.tolist(),
        'knob_mean': train_ds.knob_mean.tolist(),
        'knob_std': train_ds.knob_std.tolist(),
    }

    best_val_loss = float('inf')
    history = {'train_loss': [], 'val_loss': [], 'lr': []}

    for epoch in range(1, epochs + 1):
        # --- TRAIN ---
        model.train()
        train_losses = []
        t0 = time.time()

        for batch in train_loader:
            state = batch['state'].to(device)       # (B, 70)
            knobs = batch['knobs'].to(device)        # (B, 4)
            t_eval = batch['times'][0].to(device)    # (W,) — shared across batch
            clinical_gt = batch['clinical'].to(device)         # (B, W, C)
            crit_state_gt = batch['critical_state'].to(device) # (B, W, S)

            # Forward: Neural ODE
            clinical_pred, crit_pred = model(state, knobs, t_eval)
            # odeint returns (T, B, ...), need to permute to (B, T, ...)
            clinical_pred = clinical_pred.permute(1, 0, 2)
            crit_pred = crit_pred.permute(1, 0, 2)

            # Weighted clinical loss
            clinical_err = (clinical_pred - clinical_gt) ** 2  # (B, T, C)
            clinical_loss = (clinical_err * clinical_weights.unsqueeze(0).unsqueeze(0)).mean()

            # Critical state loss
            crit_loss = ((crit_pred - crit_state_gt) ** 2).mean()

            # ODE function regularization: penalize large derivatives
            # to encourage smooth latent dynamics
            z0 = model.encoder(state, knobs)
            model.ode_func.set_knobs(knobs)
            dzdt = model.ode_func(torch.tensor(0.0, device=device), z0)
            reg_loss = 0.01 * (dzdt ** 2).mean()

            loss = clinical_loss + 0.5 * crit_loss + reg_loss

            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 10.0)
            optimizer.step()

            train_losses.append(loss.item())

        scheduler.step()
        avg_train = np.mean(train_losses)

        # --- VALIDATE ---
        model.eval()
        val_losses = []

        with torch.no_grad():
            for batch in val_loader:
                state = batch['state'].to(device)
                knobs = batch['knobs'].to(device)
                t_eval = batch['times'][0].to(device)
                clinical_gt = batch['clinical'].to(device)
                crit_state_gt = batch['critical_state'].to(device)

                clinical_pred, crit_pred = model(state, knobs, t_eval)
                clinical_pred = clinical_pred.permute(1, 0, 2)
                crit_pred = crit_pred.permute(1, 0, 2)

                clinical_err = (clinical_pred - clinical_gt) ** 2
                clinical_loss = (clinical_err * clinical_weights.unsqueeze(0).unsqueeze(0)).mean()
                crit_loss = ((crit_pred - crit_state_gt) ** 2).mean()
                loss = clinical_loss + 0.5 * crit_loss

                val_losses.append(loss.item())

        avg_val = np.mean(val_losses) if val_losses else float('inf')

        elapsed = time.time() - t0
        lr_now = scheduler.get_last_lr()[0]
        history['train_loss'].append(avg_train)
        history['val_loss'].append(avg_val)
        history['lr'].append(lr_now)

        if epoch % 5 == 0 or epoch == 1:
            print(f"Epoch {epoch:3d}/{epochs} | "
                  f"train={avg_train:.4f} val={avg_val:.4f} | "
                  f"lr={lr_now:.6f} | {elapsed:.1f}s")

        # Save best
        if avg_val < best_val_loss:
            best_val_loss = avg_val
            save_path = os.path.join(save_dir, 'best_model.pt')
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_loss': best_val_loss,
                'latent_dim': latent_dim,
                'norm_stats': norm_stats,
                'config': {
                    'latent_dim': latent_dim,
                    'window_size': window_size,
                    'n_clinical': N_CLINICAL,
                    'n_critical': N_CRITICAL,
                    'clinical_keys': CLINICAL_KEYS,
                },
            }, save_path)
            if epoch % 5 == 0:
                print(f"  -> Saved best model (val={best_val_loss:.4f})")

        # Periodic checkpoint
        if epoch % 25 == 0:
            ckpt_path = os.path.join(save_dir, f'checkpoint_epoch{epoch}.pt')
            torch.save({
                'epoch': epoch,
                'model_state_dict': model.state_dict(),
                'optimizer_state_dict': optimizer.state_dict(),
                'val_loss': avg_val,
                'latent_dim': latent_dim,
                'norm_stats': norm_stats,
            }, ckpt_path)

    # Save final
    final_path = os.path.join(save_dir, 'final_model.pt')
    torch.save({
        'epoch': epochs,
        'model_state_dict': model.state_dict(),
        'val_loss': avg_val,
        'latent_dim': latent_dim,
        'norm_stats': norm_stats,
        'config': {
            'latent_dim': latent_dim,
            'window_size': window_size,
            'n_clinical': N_CLINICAL,
            'n_critical': N_CRITICAL,
            'clinical_keys': CLINICAL_KEYS,
        },
    }, final_path)

    # Save training history
    hist_path = os.path.join(save_dir, 'training_history.json')
    with open(hist_path, 'w') as f:
        json.dump(history, f)

    print(f"\nTraining complete. Best val loss: {best_val_loss:.4f}")
    print(f"Model saved to {save_dir}")
    return model


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', type=str, default=None)
    parser.add_argument('--epochs', type=int, default=200)
    parser.add_argument('--batch_size', type=int, default=64)
    parser.add_argument('--lr', type=float, default=1e-3)
    parser.add_argument('--window_size', type=int, default=24)
    parser.add_argument('--stride', type=int, default=6)
    parser.add_argument('--latent_dim', type=int, default=LATENT_DIM)
    parser.add_argument('--device', type=str, default=None)
    args = parser.parse_args()

    if args.data is None:
        args.data = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 'training_data.h5')
    if not os.path.exists(args.data):
        print(f"Training data not found: {args.data}")
        print("Run generate_training_data.py first.")
        sys.exit(1)

    train(args.data, epochs=args.epochs, batch_size=args.batch_size,
          lr=args.lr, window_size=args.window_size, stride=args.stride,
          latent_dim=args.latent_dim,
          device=torch.device(args.device) if args.device else None)
